language: java
jdk: oraclejdk21
services:
  - postgresql
env:
  global:
    - PGUSER=postgres
    - PGPASSWORD=postgres

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'postgres';" -U postgres
